<a href="https://colab.research.google.com/github/OkyereBiew/bayesian-credit-risk-simulator/blob/main/notebooks/02_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
column_names = [
    "checking_account",
    "duration",
    "credit_history",
    "purpose",
    "credit_amount",
    "savings_account",
    "employment_duration",
    "installment_rate",
    "personal_status_sex",
    "other_debtors",
    "residence_duration",
    "property",
    "age",
    "other_installment_plans",
    "housing",
    "existing_credits",
    "job",
    "people_liable",
    "telephone",
    "foreign_worker",
    "target"
]

In [3]:
df = pd.read_csv(
    "german.data",
    sep=" ",
    header=None,
    names=column_names
)

df.head()

,checking_account,duration,credit_history,purpose,credit_amount,savings_account,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,existing_credits,job,people_liable,telephone,foreign_worker,target
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [4]:
df["target"] = df["target"].map({
    1: 0,
    2: 1
})

df["target"].value_counts()

target
0    700
1    300
Name: count, dtype: int64

In [5]:
categorical_columns = df.select_dtypes(include=["object"]).columns

print(categorical_columns)

Index(['checking_account', 'credit_history', 'purpose', 'savings_account',
       'employment_duration', 'personal_status_sex', 'other_debtors',
       'property', 'other_installment_plans', 'housing', 'job', 'telephone',
       'foreign_worker'],
      dtype='object')

In [6]:
label_encoders = {}

for column in categorical_columns:

    encoder = LabelEncoder()

    df[column] = encoder.fit_transform(df[column])

    label_encoders[column] = encoder

In [7]:
df.head()

,checking_account,duration,credit_history,purpose,credit_amount,savings_account,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,existing_credits,job,people_liable,telephone,foreign_worker,target
0,0,6,4,4,1169,4,4,4,2,0,...,0,67,2,1,2,2,1,1,0,0
1,1,48,2,4,5951,0,2,2,1,0,...,0,22,2,1,1,2,1,0,0,1
2,3,12,4,7,2096,0,3,2,2,0,...,0,49,2,1,1,1,2,0,0,0
3,0,42,2,3,7882,0,3,2,2,2,...,1,45,2,2,1,2,2,0,0,0
4,0,24,3,0,4870,0,2,3,2,0,...,3,53,2,2,2,2,2,0,0,1

In [8]:
X = df.drop("target", axis=1)

y = df["target"]

In [9]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [10]:
print("Feature Matrix Shape:", X_scaled.shape)
print("Target Shape:", y.shape)

Feature Matrix Shape: (1000, 20)
Target Shape: (1000,)

In [11]:
print(df.describe())

       checking_account     duration  credit_history      purpose  \
count       1000.000000  1000.000000      1000.00000  1000.000000
mean           1.577000    20.903000         2.54500     3.277000
std            1.257638    12.058814         1.08312     2.739302
min            0.000000     4.000000         0.00000     0.000000
25%            0.000000    12.000000         2.00000     1.000000
50%            1.000000    18.000000         2.00000     3.000000
75%            3.000000    24.000000         4.00000     4.000000
max            3.000000    72.000000         4.00000     9.000000

       credit_amount  savings_account  employment_duration  installment_rate  \
count    1000.000000      1000.000000          1000.000000       1000.000000
mean     3271.258000         1.105000             2.384000          2.973000
std      2822.736876         1.580023             1.208306          1.118715
min       250.000000         0.000000             0.000000          1.000000
25%      1365.500000         0.000000             2.000000          2.000000
50%      2319.500000         0.000000             2.000000          3.000000
75%      3972.250000         2.000000             4.000000          4.000000
max     18424.000000         4.000000             4.000000          4.000000

       personal_status_sex  other_debtors  ...     property          age  \
count           1000.00000    1000.000000  ...  1000.000000  1000.000000
mean               1.68200       0.145000  ...     1.358000    35.546000
std                0.70808       0.477706  ...     1.050209    11.375469
min                0.00000       0.000000  ...     0.000000    19.000000
25%                1.00000       0.000000  ...     0.000000    27.000000
50%                2.00000       0.000000  ...     1.000000    33.000000
75%                2.00000       0.000000  ...     2.000000    42.000000
max                3.00000       2.000000  ...     3.000000    75.000000

       other_installment_plans      housing  existing_credits          job  \
count              1000.000000  1000.000000       1000.000000  1000.000000
mean                  1.675000     0.929000          1.407000     1.904000
std                   0.705601     0.531264          0.577654     0.653614
min                   0.000000     0.000000          1.000000     0.000000
25%                   2.000000     1.000000          1.000000     2.000000
50%                   2.000000     1.000000          1.000000     2.000000
75%                   2.000000     1.000000          2.000000     2.000000
max                   2.000000     2.000000          4.000000     3.000000

       people_liable    telephone  foreign_worker       target
count    1000.000000  1000.000000     1000.000000  1000.000000
mean        1.155000     0.404000        0.037000     0.300000
std         0.362086     0.490943        0.188856     0.458487
min         1.000000     0.000000        0.000000     0.000000
25%         1.000000     0.000000        0.000000     0.000000
50%         1.000000     0.000000        0.000000     0.000000
75%         1.000000     1.000000        0.000000     1.000000
max         2.000000     1.000000        1.000000     1.000000

[8 rows x 21 columns]